apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app
  description: Simple “Hello World” for Backstage demo
  tags:
    - demo
    - hello-world
  annotations:
    github.com/project-slug: your-org/hello-world
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:antoguerra
  providesApis: [hello-world-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world-api
  description: Dummy ping endpoint exposed by the FastAPI service
spec:
  type: openapi
  lifecycle: experimental
  owner: user:antoguerra
  definition:
    $text: ./openapi.json